workflows:
  ios -free-build:
    name: i0S Free Accounts Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter dependencies
        script: flutter packages pub get
      - name: Build unsigned iOS IPA
        script: |
          #   The --no-codesign flag is critical for free accounts flutter 
          build ios --release --no-codesign 
        
          # Manually package the app into a •ipa structure 
          mkdir -p build/ios/iphoneos/Payload
          cp-rbuild/ios/iphones/Runner.app build/ios/iphones/Payload/ 
          cd build/ios/iphones &å zip -r unsigned_app.ipa Payload
    artifacts:
        - build/ios/iphoneos/unsigned_app.ipa